export const extensionData = [
  {
    id: 'ext001',
    name: 'TabMaster',
    slug: 'tabmaster',
    shortDescription:
      'Organize your tabs with customizable groups and quick access.',
    fullDescription:
      'TabMaster helps you manage your browser tabs efficiently by creating groups and saving sessions for later.',
    developer: { id: 'dev101', name: 'Alice Dev', verified: true },
    category: ['Productivity', 'Tab Management'],
    tags: ['tabs', 'productivity', 'session'],
    logo: 'https://example.com/extensions/tabmaster/logo.png',
    screenshots: [
      'https://example.com/extensions/tabmaster/screen1.png',
      'https://example.com/extensions/tabmaster/screen2.png',
    ],
    chromeStoreUrl:
      'https://chrome.google.com/webstore/detail/tabmaster/abcd1234',
    averageRating: 4.6,
    totalReviews: 152,
    ratingDistribution: { '1': 5, '2': 3, '3': 10, '4': 45, '5': 89 },
    status: 'approved',
    featured: true,
    underrated: false,
    overrated: false,
    trending: true,
    submissionDate: '2025-03-25T10:20:30Z',
    lastUpdated: '2025-08-10T14:56:12Z',
    views: 18000,
    likes: 11000,
    dislikes: 200,
    bookmarks: 4000,
    version: '2.4.1',
    permissions: ['tabs', 'storage', 'sessions'],
    website: 'https://tabmaster.dev',
    github: 'https://github.com/tabmaster/tabmaster',
  },
  {
    id: 'ext002',
    name: 'PrivacyGuard',
    slug: 'privacyguard',
    shortDescription:
      'Block trackers and protect your online privacy effortlessly.',
    fullDescription:
      'PrivacyGuard blocks third-party trackers, cookies, and scripts, offering enhanced privacy and faster browsing.',
    developer: { id: 'dev102', name: 'Bob Builder', verified: false },
    category: ['Privacy', 'Security'],
    tags: ['privacy', 'ad blocker', 'tracker'],
    logo: 'https://example.com/extensions/privacyguard/logo.png',
    screenshots: ['https://example.com/extensions/privacyguard/screen1.png'],
    chromeStoreUrl:
      'https://chrome.google.com/webstore/detail/privacyguard/wxyz5678',
    averageRating: 4.8,
    totalReviews: 70,
    ratingDistribution: { '1': 1, '2': 0, '3': 4, '4': 20, '5': 45 },
    status: 'approved',
    featured: false,
    underrated: true,
    overrated: false,
    trending: false,
    submissionDate: '2024-12-12T09:15:00Z',
    lastUpdated: '2025-07-05T18:10:45Z',
    views: 3000,
    likes: 2800,
    dislikes: 20,
    bookmarks: 900,
    version: '1.9.7',
    permissions: ['webRequest', 'storage', 'cookies'],
    website: null,
    github: 'https://github.com/privacyguard/privacyguard',
  },
  {
    id: 'ext003',
    name: 'MegaClipboard',
    slug: 'megaclipboard',
    shortDescription:
      'Enhance your clipboard with history, search, and favorites.',
    fullDescription:
      'MegaClipboard records your clipboard history, lets you search past copies, and save favorites for quick reuse.',
    developer: { id: 'dev103', name: 'Carol Coder', verified: true },
    category: ['Productivity', 'Utilities'],
    tags: ['clipboard', 'productivity', 'history'],
    logo: 'https://example.com/extensions/megaclipboard/logo.png',
    screenshots: [
      'https://example.com/extensions/megaclipboard/screen1.png',
      'https://example.com/extensions/megaclipboard/screen2.png',
      'https://example.com/extensions/megaclipboard/screen3.png',
    ],
    chromeStoreUrl:
      'https://chrome.google.com/webstore/detail/megaclipboard/ijkl9012',
    averageRating: 4.2,
    totalReviews: 230,
    ratingDistribution: { '1': 9, '2': 11, '3': 30, '4': 80, '5': 100 },
    status: 'approved',
    featured: false,
    underrated: false,
    overrated: true,
    trending: false,
    submissionDate: '2023-07-19T16:00:00Z',
    lastUpdated: '2025-06-15T12:25:00Z',
    views: 42000,
    likes: 27000,
    dislikes: 600,
    bookmarks: 7800,
    version: '3.1.0',
    permissions: ['clipboardRead', 'storage'],
    website: 'https://megaclipboard.app',
    github: null,
  },
  {
    id: 'ext004',
    name: 'DarkMode Pro',
    slug: 'darkmode-pro',
    shortDescription: 'Automatic dark mode for all websites.',
    fullDescription:
      'DarkMode Pro enables system-wide dark theme for all websites with customizable themes and schedules.',
    developer: { id: 'dev104', name: 'Dana Designer', verified: true },
    category: ['Appearance', 'Productivity'],
    tags: ['dark mode', 'theme', 'night browsing'],
    logo: 'https://example.com/extensions/darkmodepro/logo.png',
    screenshots: [
      'https://example.com/extensions/darkmodepro/screen1.png',
      'https://example.com/extensions/darkmodepro/screen2.png',
    ],
    chromeStoreUrl:
      'https://chrome.google.com/webstore/detail/darkmodepro/nopq3456',
    averageRating: 4.7,
    totalReviews: 195,
    ratingDistribution: { '1': 3, '2': 7, '3': 10, '4': 80, '5': 95 },
    status: 'approved',
    featured: true,
    underrated: false,
    overrated: false,
    trending: true,
    submissionDate: '2024-05-11T13:00:00Z',
    lastUpdated: '2025-08-11T10:20:00Z',
    views: 27000,
    likes: 21500,
    dislikes: 150,
    bookmarks: 6200,
    version: '1.5.4',
    permissions: ['storage', 'activeTab'],
    website: 'https://darkmodepro.com',
    github: 'https://github.com/darkmodepro/darkmodepro',
  },
  {
    id: 'ext005',
    name: 'Grammar Checker',
    slug: 'grammar-checker',
    shortDescription: 'Correct your writing mistakes across the web.',
    fullDescription:
      'Grammar Checker highlights spelling and grammar errors in text fields and suggests corrections in real-time.',
    developer: { id: 'dev105', name: 'Eli Editor', verified: false },
    category: ['Writing', 'Productivity'],
    tags: ['grammar', 'spellcheck', 'writing assistance'],
    logo: 'https://example.com/extensions/grammarchecker/logo.png',
    screenshots: ['https://example.com/extensions/grammarchecker/screen1.png'],
    chromeStoreUrl:
      'https://chrome.google.com/webstore/detail/grammarchecker/qrst7890',
    averageRating: 4.3,
    totalReviews: 340,
    ratingDistribution: { '1': 6, '2': 15, '3': 40, '4': 110, '5': 169 },
    status: 'approved',
    featured: false,
    underrated: true,
    overrated: false,
    trending: false,
    submissionDate: '2024-03-22T08:45:00Z',
    lastUpdated: '2025-07-20T11:15:00Z',
    views: 12000,
    likes: 9000,
    dislikes: 80,
    bookmarks: 3200,
    version: '2.0.3',
    permissions: ['storage', 'activeTab'],
    website: null,
    github: null,
  },
  {
    id: 'ext006',
    name: 'Quick Screenshot',
    slug: 'quick-screenshot',
    shortDescription: 'Capture, annotate, and share screenshots fast.',
    fullDescription:
      'Quick Screenshot lets you capture full webpages, annotate images, and share directly from the browser.',
    developer: { id: 'dev106', name: 'Frank Flash', verified: true },
    category: ['Productivity', 'Utilities'],
    tags: ['screenshot', 'annotate', 'capture'],
    logo: 'https://example.com/extensions/quickscreenshot/logo.png',
    screenshots: [
      'https://example.com/extensions/quickscreenshot/screen1.png',
      'https://example.com/extensions/quickscreenshot/screen2.png',
    ],
    chromeStoreUrl:
      'https://chrome.google.com/webstore/detail/quickscreenshot/uvwx4321',
    averageRating: 4.4,
    totalReviews: 280,
    ratingDistribution: { '1': 8, '2': 10, '3': 20, '4': 110, '5': 132 },
    status: 'approved',
    featured: false,
    underrated: false,
    overrated: false,
    trending: true,
    submissionDate: '2023-11-10T15:30:00Z',
    lastUpdated: '2025-08-14T09:00:00Z',
    views: 15000,
    likes: 11200,
    dislikes: 95,
    bookmarks: 4500,
    version: '1.7.9',
    permissions: ['tabs', 'storage', 'activeTab'],
    website: 'https://quickscreenshot.app',
    github: 'https://github.com/quickscreenshot/quickscreenshot',
  },
  {
    id: 'ext007',
    name: 'FocusTimer',
    slug: 'focustimer',
    shortDescription:
      'Boost your productivity with customizable Pomodoro timers.',
    fullDescription:
      'FocusTimer allows you to create Pomodoro sessions, track progress, and block distracting sites during focus periods.',
    developer: { id: 'dev107', name: 'Grace Goals', verified: true },
    category: ['Productivity', 'Time Management'],
    tags: ['pomodoro', 'timer', 'productivity'],
    logo: 'https://example.com/extensions/focustimer/logo.png',
    screenshots: ['https://example.com/extensions/focustimer/screen1.png'],
    chromeStoreUrl:
      'https://chrome.google.com/webstore/detail/focustimer/hijk6543',
    averageRating: 4.9,
    totalReviews: 410,
    ratingDistribution: { '1': 1, '2': 2, '3': 7, '4': 85, '5': 315 },
    status: 'approved',
    featured: true,
    underrated: false,
    overrated: false,
    trending: true,
    submissionDate: '2024-08-17T10:00:00Z',
    lastUpdated: '2025-08-12T15:15:00Z',
    views: 35000,
    likes: 32500,
    dislikes: 50,
    bookmarks: 10900,
    version: '3.0.0',
    permissions: ['storage', 'tabs'],
    website: 'https://focustimer.app',
    github: 'https://github.com/focustimer/focustimer',
  },
  {
    id: 'ext008',
    name: 'ColorPicker Pro',
    slug: 'colorpicker-pro',
    shortDescription:
      'An advanced color picker with palette and eyedropper tools.',
    fullDescription:
      'ColorPicker Pro helps designers and developers pick colors easily from any webpage and manage palettes.',
    developer: { id: 'dev108', name: 'Henry Hue', verified: false },
    category: ['Design', 'Utilities'],
    tags: ['color picker', 'eyedropper', 'palette'],
    logo: 'https://example.com/extensions/colorpickerpro/logo.png',
    screenshots: ['https://example.com/extensions/colorpickerpro/screen1.png'],
    chromeStoreUrl:
      'https://chrome.google.com/webstore/detail/colorpickerpro/lmno9876',
    averageRating: 4.1,
    totalReviews: 130,
    ratingDistribution: { '1': 4, '2': 8, '3': 30, '4': 45, '5': 43 },
    status: 'approved',
    featured: false,
    underrated: true,
    overrated: false,
    trending: false,
    submissionDate: '2025-01-10T09:00:00Z',
    lastUpdated: '2025-06-30T13:30:00Z',
    views: 6000,
    likes: 4500,
    dislikes: 120,
    bookmarks: 1400,
    version: '1.3.2',
    permissions: ['activeTab', 'storage'],
    website: null,
    github: 'https://github.com/colorpickerpro/colorpickerpro',
  },
  {
    id: 'ext009',
    name: 'Markdown Editor',
    slug: 'markdown-editor',
    shortDescription: 'Write and preview Markdown in a side panel.',
    fullDescription:
      'Markdown Editor lets you write Markdown easily and see live rendered previews inside your browser.',
    developer: { id: 'dev109', name: 'Isabel Ink', verified: true },
    category: ['Writing', 'Developer Tools'],
    tags: ['markdown', 'editor', 'preview'],
    logo: 'https://example.com/extensions/markdowneditor/logo.png',
    screenshots: [
      'https://example.com/extensions/markdowneditor/screen1.png',
      'https://example.com/extensions/markdowneditor/screen2.png',
    ],
    chromeStoreUrl:
      'https://chrome.google.com/webstore/detail/markdowneditor/pqrs2109',
    averageRating: 4.5,
    totalReviews: 210,
    ratingDistribution: { '1': 3, '2': 5, '3': 20, '4': 90, '5': 92 },
    status: 'approved',
    featured: false,
    underrated: false,
    overrated: false,
    trending: true,
    submissionDate: '2023-10-05T11:10:00Z',
    lastUpdated: '2025-07-29T17:45:00Z',
    views: 18000,
    likes: 13000,
    dislikes: 150,
    bookmarks: 5500,
    version: '2.5.1',
    permissions: ['storage'],
    website: 'https://markdowneditor.dev',
    github: 'https://github.com/markdowneditor/markdowneditor',
  },
  {
    id: 'ext010',
    name: 'Speedy VPN',
    slug: 'speedy-vpn',
    shortDescription: 'One-click VPN to secure your online browsing instantly.',
    fullDescription:
      'Speedy VPN offers fast and secure VPN connectivity with a simple one-click interface to protect privacy and bypass restrictions.',
    developer: { id: 'dev110', name: 'Jake Jet', verified: false },
    category: ['Privacy', 'Utilities'],
    tags: ['vpn', 'privacy', 'security'],
    logo: 'https://example.com/extensions/speedyvpn/logo.png',
    screenshots: [
      'https://example.com/extensions/speedyvpn/screen1.png',
      'https://example.com/extensions/speedyvpn/screen2.png',
    ],
    chromeStoreUrl:
      'https://chrome.google.com/webstore/detail/speedyvpn/stuv4321',
    averageRating: 4.0,
    totalReviews: 95,
    ratingDistribution: { '1': 7, '2': 10, '3': 25, '4': 30, '5': 23 },
    status: 'approved',
    featured: false,
    underrated: true,
    overrated: false,
    trending: false,
    submissionDate: '2025-04-01T13:20:00Z',
    lastUpdated: '2025-08-01T10:40:00Z',
    views: 8000,
    likes: 6000,
    dislikes: 100,
    bookmarks: 2100,
    version: '1.1.0',
    permissions: ['proxy', 'storage'],
    website: null,
    github: null,
  },
];

export function getExtensionById(id: string) {
  return extensionData.find(extension => extension.id === id);
}
